-- Generated by Oracle SQL Developer Data Modeler 4.0.1.836
--   at:        2014-06-25 18:57:41 CEST
--   site:      SQL Server 2008
--   type:      SQL Server 2008




CREATE
  TABLE Uprawnienia
  (
    Funkcja            VARCHAR (64) NOT NULL ,
    Has這          VARCHAR (64) NOT NULL ,
    Uprawnienia_ID NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION ,
    CONSTRAINT Uprawnienia_PK PRIMARY KEY CLUSTERED (Uprawnienia_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE U篡tkownik
  (
    U篡tkownik_ID              NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION ,
    Nazwa                      VARCHAR (64) NOT NULL ,
    Has這                      VARCHAR (64) NOT NULL ,
    Uprawnienia_Uprawnienia_ID NUMERIC (28) NOT NULL ,
    CONSTRAINT U篡tkownik_PK PRIMARY KEY CLUSTERED (U篡tkownik_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

ALTER TABLE U篡tkownik
ADD CONSTRAINT U篡tkownik_Uprawnienia_FK FOREIGN KEY
(
Uprawnienia_Uprawnienia_ID
)
REFERENCES Uprawnienia
(
Uprawnienia_ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             2
-- CREATE INDEX                             0
-- ALTER TABLE                              1
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


INSERT INTO [dbo].[Uprawnienia]
           ([Funkcja], [Has這])
     VALUES
           ('Sprzedawca', 'Sprzedawca1'),
		   ('Serwisant', 'Serwisant1'),
		   ('Kadrowy', 'Kadrowy1'),
		   ('Admin', 'Admin1')

insert into U篡tkownik(Nazwa, Has這, Uprawnienia_Uprawnienia_ID) values('Krysia', '12345', 1)